import type { Lesson, RegionalTrack, RegionSlug } from "./types";

type RegionSeed = Omit<RegionalTrack, "lessons" | "quiz"> & {
  lessonTitle: string;
  lessonSummary: string;
  objectives: string[];
  knowledgeHeading: string;
  knowledgeParagraphs: string[];
  listItems: string[];
  calloutTitle: string;
  calloutText: string;
  quizTitle: string;
  questions: RegionalTrack["quiz"]["questions"];
};

function createRegionalLesson(region: RegionSeed): Lesson {
  return {
    slug: "genlayer-basics",
    title: region.lessonTitle,
    durationMinutes: 10,
    summary: region.lessonSummary,
    objectives: region.objectives,
    content: [
      { type: "heading", text: region.knowledgeHeading },
      ...region.knowledgeParagraphs.map((text) => ({ type: "paragraph" as const, text })),
      { type: "list", items: region.listItems },
      { type: "callout", title: region.calloutTitle, text: region.calloutText },
    ],
  };
}

function createRegionalTrack(region: RegionSeed): RegionalTrack {
  return {
    slug: region.slug,
    regionName: region.regionName,
    nativeRegionName: region.nativeRegionName,
    languageName: region.languageName,
    nativeLanguageName: region.nativeLanguageName,
    locale: region.locale,
    title: region.title,
    description: region.description,
    unityMessage: region.unityMessage,
    certificateTitle: region.certificateTitle,
    lessons: [createRegionalLesson(region)],
    quiz: {
      slug: `${region.slug}-genlayer-basics-quiz`,
      title: region.quizTitle,
      passPercent: 70,
      questions: region.questions,
    },
  };
}

export const regionalTracks: RegionalTrack[] = [
  createRegionalTrack({
    slug: "china",
    regionName: "China",
    nativeRegionName: "中国",
    languageName: "Chinese",
    nativeLanguageName: "中文",
    locale: "zh-CN",
    title: "GenLayer 中文基础课",
    description: "用中文理解 GenLayer、智能合约和 AI 原生验证。",
    unityMessage: "中国社区和全球成员一起学习同一个 GenLayer 语言：理解、建设、共享。",
    certificateTitle: "GenLayer 中文基础证书",
    lessonTitle: "GenLayer 基础知识",
    lessonSummary: "快速了解 GenLayer 为什么适合需要判断和上下文的链上应用。",
    objectives: ["理解 GenLayer 是 AI 原生 Layer 1。", "认识 Python 智能合约。", "理解主观验证为什么重要。"],
    knowledgeHeading: "GenLayer 是什么？",
    knowledgeParagraphs: [
      "GenLayer 是一个 AI 原生的 Layer 1 区块链。它不仅处理固定规则，也帮助合约处理需要上下文和判断的问题。",
      "智能合约使用 Python 编写，可以把学习、证书、评估和社区贡献等流程变得更透明。",
    ],
    listItems: ["AI 原生验证", "Python 智能合约", "适合主观和真实世界数据的应用"],
    calloutTitle: "社区重点",
    calloutText: "学习 GenLayer 的目标不是背术语，而是理解它如何帮助全球社区一起建立可信应用。",
    quizTitle: "GenLayer 中文基础测验",
    questions: [
      { id: "china-q1", prompt: "GenLayer 智能合约主要使用什么语言？", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer 智能合约使用 Python 编写。" },
      { id: "china-q2", prompt: "GenLayer 特别适合哪类问题？", options: ["只做简单转账", "需要上下文和判断的问题", "只存图片", "不需要验证的问题"], correctOption: 1, explanation: "GenLayer 的 AI 原生验证适合主观和上下文丰富的场景。" },
      { id: "china-q3", prompt: "社区学习 GenLayer 的核心价值是什么？", options: ["只追价格", "理解并建设可信应用", "避免学习合约", "只复制代码"], correctOption: 1, explanation: "GenLayer School 关注理解、建设和社区协作。" },
    ],
  }),
  createRegionalTrack({
    slug: "india",
    regionName: "India",
    nativeRegionName: "भारत",
    languageName: "Hindi",
    nativeLanguageName: "हिन्दी",
    locale: "hi-IN",
    title: "GenLayer हिंदी मूल बातें",
    description: "हिंदी में GenLayer, Intelligent Contracts और AI-native validation सीखें।",
    unityMessage: "भारत के सदस्य अपनी भाषा में सीखते हुए GenLayer की वैश्विक कम्युनिटी से जुड़ते हैं।",
    certificateTitle: "GenLayer हिंदी बेसिक्स सर्टिफिकेट",
    lessonTitle: "GenLayer की बुनियादी समझ",
    lessonSummary: "GenLayer को सरल भाषा में समझें: AI-native chain, Python contracts और community learning.",
    objectives: ["GenLayer को AI-native Layer 1 के रूप में समझना।", "Python Intelligent Contracts को पहचानना।", "Subjective validation का उपयोग समझना।"],
    knowledgeHeading: "GenLayer क्या है?",
    knowledgeParagraphs: [
      "GenLayer एक AI-native Layer 1 blockchain है। यह ऐसे apps के लिए बना है जहां जवाब हमेशा simple calculation नहीं होता।",
      "Intelligent Contracts Python में लिखे जाते हैं और वे context-aware decisions के लिए उपयोगी हो सकते हैं।",
    ],
    listItems: ["Python contracts", "AI validators", "learning, reputation और certificates के लिए useful"],
    calloutTitle: "Community focus",
    calloutText: "Native language में सीखना ज्यादा लोगों को GenLayer समझने और बनाने में मदद करता है।",
    quizTitle: "GenLayer हिंदी क्विज",
    questions: [
      { id: "india-q1", prompt: "GenLayer Intelligent Contracts किस language में लिखे जाते हैं?", options: ["Python", "Solidity", "Cairo", "Move"], correctOption: 0, explanation: "GenLayer Intelligent Contracts Python में लिखे जाते हैं।" },
      { id: "india-q2", prompt: "GenLayer किस तरह के decisions के लिए अच्छा है?", options: ["Only fixed arithmetic", "Context और judgment वाले decisions", "Only file storage", "No validation"], correctOption: 1, explanation: "GenLayer AI-native validation के साथ subjective decisions को support करता है।" },
      { id: "india-q3", prompt: "Regional learning का फायदा क्या है?", options: ["Learning को मुश्किल बनाना", "Native language में समझ बढ़ाना", "Community को अलग करना", "Quizzes हटाना"], correctOption: 1, explanation: "Native language learning से ज्यादा members ecosystem समझ पाते हैं।" },
    ],
  }),
  createRegionalTrack({
    slug: "indonesia",
    regionName: "Indonesia",
    nativeRegionName: "Indonesia",
    languageName: "Indonesian",
    nativeLanguageName: "Bahasa Indonesia",
    locale: "id-ID",
    title: "Dasar GenLayer Bahasa Indonesia",
    description: "Pelajari GenLayer, Intelligent Contracts, dan validasi AI-native dalam Bahasa Indonesia.",
    unityMessage: "Komunitas Indonesia belajar dengan bahasa sendiri dan tetap terhubung dengan gerakan GenLayer global.",
    certificateTitle: "Sertifikat Dasar GenLayer Indonesia",
    lessonTitle: "Pengenalan GenLayer",
    lessonSummary: "Pahami GenLayer sebagai blockchain AI-native untuk keputusan yang membutuhkan konteks.",
    objectives: ["Menjelaskan GenLayer sebagai Layer 1 AI-native.", "Mengenali Intelligent Contracts berbasis Python.", "Memahami validasi subjektif."],
    knowledgeHeading: "Apa itu GenLayer?",
    knowledgeParagraphs: [
      "GenLayer adalah blockchain Layer 1 AI-native. Ia membantu aplikasi menangani keputusan yang tidak selalu bisa dijawab dengan aturan kaku.",
      "Dengan Intelligent Contracts berbasis Python, komunitas dapat membangun alur sertifikat, reputasi, evaluasi, dan pembelajaran yang lebih transparan.",
    ],
    listItems: ["AI-native Layer 1", "Kontrak dalam Python", "Cocok untuk keputusan berbasis konteks"],
    calloutTitle: "Untuk komunitas",
    calloutText: "Belajar dalam bahasa lokal membuat lebih banyak anggota bisa ikut memahami dan membangun di GenLayer.",
    quizTitle: "Kuis Dasar GenLayer Indonesia",
    questions: [
      { id: "indonesia-q1", prompt: "Bahasa utama untuk Intelligent Contracts GenLayer adalah apa?", options: ["Python", "Solidity", "Rust", "Move"], correctOption: 0, explanation: "Intelligent Contracts GenLayer ditulis dengan Python." },
      { id: "indonesia-q2", prompt: "GenLayer kuat untuk keputusan seperti apa?", options: ["Hanya angka tetap", "Keputusan yang butuh konteks", "Hanya menyimpan gambar", "Tanpa validator"], correctOption: 1, explanation: "GenLayer dirancang untuk validasi AI-native dan keputusan subjektif." },
      { id: "indonesia-q3", prompt: "Apa tujuan belajar regional?", options: ["Memisahkan komunitas", "Membuat GenLayer lebih mudah dipahami", "Menghapus kuis", "Menghindari praktik"], correctOption: 1, explanation: "Bahasa lokal membantu anggota memahami konsep dengan lebih cepat." },
    ],
  }),
  createRegionalTrack({
    slug: "latam",
    regionName: "LATAM",
    nativeRegionName: "Latinoamérica",
    languageName: "Spanish",
    nativeLanguageName: "Español",
    locale: "es-419",
    title: "Fundamentos de GenLayer en Español",
    description: "Aprende GenLayer, contratos inteligentes en Python y validación AI-native en español.",
    unityMessage: "LATAM aprende GenLayer en español y se une a una comunidad global que construye junta.",
    certificateTitle: "Certificado GenLayer Básico LATAM",
    lessonTitle: "Introducción a GenLayer",
    lessonSummary: "Una explicación breve de GenLayer para miembros de la comunidad LATAM.",
    objectives: ["Entender GenLayer como una Layer 1 AI-native.", "Reconocer Intelligent Contracts en Python.", "Explicar por qué importa la validación subjetiva."],
    knowledgeHeading: "¿Qué es GenLayer?",
    knowledgeParagraphs: [
      "GenLayer es una blockchain Layer 1 AI-native diseñada para aplicaciones donde algunas respuestas requieren contexto y criterio.",
      "Los Intelligent Contracts se escriben en Python y pueden ayudar a crear credenciales, evaluaciones y flujos comunitarios verificables.",
    ],
    listItems: ["Contratos en Python", "Validación con IA", "Útil para educación, reputación y certificaciones"],
    calloutTitle: "Mensaje regional",
    calloutText: "Aprender en español permite que más miembros de LATAM entiendan GenLayer y participen en el ecosistema global.",
    quizTitle: "Quiz GenLayer Básico LATAM",
    questions: [
      { id: "latam-q1", prompt: "¿En qué lenguaje se escriben los Intelligent Contracts de GenLayer?", options: ["Python", "Solidity", "Move", "Cairo"], correctOption: 0, explanation: "Los Intelligent Contracts de GenLayer se escriben en Python." },
      { id: "latam-q2", prompt: "¿Para qué tipo de decisiones sirve GenLayer?", options: ["Solo cálculos fijos", "Decisiones con contexto y criterio", "Solo guardar archivos", "Decisiones sin validación"], correctOption: 1, explanation: "GenLayer soporta validación AI-native para decisiones subjetivas." },
      { id: "latam-q3", prompt: "¿Por qué importa aprender en idioma nativo?", options: ["Porque reduce la comprensión", "Porque abre la puerta a más miembros", "Porque elimina la comunidad", "Porque evita construir"], correctOption: 1, explanation: "El idioma nativo ayuda a más personas a participar con confianza." },
    ],
  }),
  createRegionalTrack({
    slug: "nigeria",
    regionName: "Nigeria",
    nativeRegionName: "Naija",
    languageName: "Pidgin",
    nativeLanguageName: "Naija Pidgin",
    locale: "pcm-NG",
    title: "GenLayer Basic for Naija Pidgin",
    description: "Learn GenLayer for Pidgin: AI-native chain, Python contracts, and community certificates.",
    unityMessage: "Naija community fit learn GenLayer for our own voice and still build with the whole world.",
    certificateTitle: "GenLayer Naija Pidgin Basics Certificate",
    lessonTitle: "Wetin be GenLayer?",
    lessonSummary: "Simple Pidgin intro to GenLayer and why e matter for community builders.",
    objectives: ["Know say GenLayer na AI-native Layer 1.", "Understand say Intelligent Contracts dey use Python.", "Know why context and judgement matter."],
    knowledgeHeading: "GenLayer na wetin?",
    knowledgeParagraphs: [
      "GenLayer na AI-native Layer 1 blockchain. E dey useful when answer no be only simple calculation, but matter need context and judgement.",
      "Intelligent Contracts dey use Python. With am, community fit build learning records, certificates, reputation, and apps wey need better verification.",
    ],
    listItems: ["AI-native validation", "Python Intelligent Contracts", "Useful for learning, certificates, and community trust"],
    calloutTitle: "Community sense",
    calloutText: "When people learn for language wey dem dey comfortable with, more builders fit enter GenLayer and build together.",
    quizTitle: "GenLayer Naija Pidgin Quiz",
    questions: [
      { id: "nigeria-q1", prompt: "GenLayer Intelligent Contracts dey use which language?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer Intelligent Contracts dey use Python." },
      { id: "nigeria-q2", prompt: "GenLayer good for which kind matter?", options: ["Only fixed calculation", "Matter wey need context and judgement", "Only picture storage", "Matter wey no need validation"], correctOption: 1, explanation: "GenLayer AI-native validation fit help for subjective decisions." },
      { id: "nigeria-q3", prompt: "Why Pidgin learning matter?", options: ["E make learning harder", "E help more Naija members understand", "E remove community", "E stop builders"], correctOption: 1, explanation: "Native/community language fit bring more people into the ecosystem." },
    ],
  }),
  createRegionalTrack({
    slug: "russia",
    regionName: "Russia",
    nativeRegionName: "Россия",
    languageName: "Russian",
    nativeLanguageName: "Русский",
    locale: "ru-RU",
    title: "Основы GenLayer на русском",
    description: "Изучайте GenLayer, Python Intelligent Contracts и AI-native валидацию на русском языке.",
    unityMessage: "Русскоязычное сообщество изучает GenLayer на родном языке и остается частью глобального движения.",
    certificateTitle: "Сертификат GenLayer Basics Russia",
    lessonTitle: "Введение в GenLayer",
    lessonSummary: "Короткое объяснение GenLayer для русскоязычных участников сообщества.",
    objectives: ["Понять GenLayer как AI-native Layer 1.", "Узнать, что Intelligent Contracts пишутся на Python.", "Понять роль субъективной проверки."],
    knowledgeHeading: "Что такое GenLayer?",
    knowledgeParagraphs: [
      "GenLayer — это AI-native Layer 1 блокчейн для приложений, где ответ может требовать контекста и оценки.",
      "Intelligent Contracts пишутся на Python и могут использоваться для обучения, сертификатов, репутации и других проверяемых процессов.",
    ],
    listItems: ["AI-native валидация", "Python Intelligent Contracts", "Подходит для контекстных решений"],
    calloutTitle: "Для сообщества",
    calloutText: "Обучение на родном языке помогает большему числу участников понимать GenLayer и строить вместе.",
    quizTitle: "Тест по основам GenLayer",
    questions: [
      { id: "russia-q1", prompt: "На каком языке пишутся Intelligent Contracts в GenLayer?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "Intelligent Contracts в GenLayer пишутся на Python." },
      { id: "russia-q2", prompt: "Для каких решений GenLayer особенно полезен?", options: ["Только простая арифметика", "Решения с контекстом и оценкой", "Только хранение файлов", "Без проверки"], correctOption: 1, explanation: "GenLayer поддерживает AI-native проверку субъективных решений." },
      { id: "russia-q3", prompt: "Зачем нужна региональная школа?", options: ["Чтобы разделить людей", "Чтобы учиться понятнее на родном языке", "Чтобы убрать практику", "Чтобы скрыть знания"], correctOption: 1, explanation: "Родной язык делает обучение доступнее." },
    ],
  }),
  createRegionalTrack({
    slug: "korea",
    regionName: "Korea",
    nativeRegionName: "한국",
    languageName: "Korean",
    nativeLanguageName: "한국어",
    locale: "ko-KR",
    title: "GenLayer 한국어 기초",
    description: "한국어로 GenLayer, Python Intelligent Contracts, AI-native 검증을 배웁니다.",
    unityMessage: "한국 커뮤니티가 한국어로 배우고 전 세계 GenLayer 커뮤니티와 함께 성장합니다.",
    certificateTitle: "GenLayer 한국어 기초 인증서",
    lessonTitle: "GenLayer 소개",
    lessonSummary: "GenLayer가 왜 문맥과 판단이 필요한 앱에 중요한지 간단히 배웁니다.",
    objectives: ["GenLayer를 AI-native Layer 1으로 이해하기.", "Python Intelligent Contracts 이해하기.", "주관적 검증의 의미 이해하기."],
    knowledgeHeading: "GenLayer란 무엇인가요?",
    knowledgeParagraphs: [
      "GenLayer는 AI-native Layer 1 블록체인입니다. 단순 계산만이 아니라 문맥과 판단이 필요한 상황을 다룰 수 있도록 설계되었습니다.",
      "Intelligent Contracts는 Python으로 작성되며, 학습 기록, 인증서, 평판, 커뮤니티 검증에 활용될 수 있습니다.",
    ],
    listItems: ["AI-native 검증", "Python 계약", "교육과 인증에 적합"],
    calloutTitle: "커뮤니티 메시지",
    calloutText: "모국어로 배우면 더 많은 커뮤니티 멤버가 GenLayer를 이해하고 함께 만들 수 있습니다.",
    quizTitle: "GenLayer 한국어 기초 퀴즈",
    questions: [
      { id: "korea-q1", prompt: "GenLayer Intelligent Contracts는 어떤 언어로 작성되나요?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer Intelligent Contracts는 Python으로 작성됩니다." },
      { id: "korea-q2", prompt: "GenLayer는 어떤 결정에 강점이 있나요?", options: ["고정 계산만", "문맥과 판단이 필요한 결정", "이미지 저장만", "검증 없는 결정"], correctOption: 1, explanation: "GenLayer는 AI-native 검증으로 주관적 결정을 지원합니다." },
      { id: "korea-q3", prompt: "지역별 학습의 장점은 무엇인가요?", options: ["이해를 어렵게 함", "모국어로 접근성을 높임", "커뮤니티를 없앰", "퀴즈를 제거함"], correctOption: 1, explanation: "모국어 학습은 더 넓은 참여를 만듭니다." },
    ],
  }),
  createRegionalTrack({
    slug: "turkey",
    regionName: "Turkey",
    nativeRegionName: "Türkiye",
    languageName: "Turkish",
    nativeLanguageName: "Türkçe",
    locale: "tr-TR",
    title: "Türkçe GenLayer Temelleri",
    description: "GenLayer, Python Intelligent Contracts ve AI-native doğrulamayı Türkçe öğrenin.",
    unityMessage: "Türkiye topluluğu kendi dilinde öğrenirken küresel GenLayer topluluğuyla birlikte hareket eder.",
    certificateTitle: "GenLayer Türkiye Temel Sertifikası",
    lessonTitle: "GenLayer'a Giriş",
    lessonSummary: "GenLayer'ın bağlam ve yorum gerektiren uygulamalar için neden önemli olduğunu öğrenin.",
    objectives: ["GenLayer'ı AI-native Layer 1 olarak anlamak.", "Python Intelligent Contracts fikrini tanımak.", "Subjektif doğrulamanın önemini görmek."],
    knowledgeHeading: "GenLayer nedir?",
    knowledgeParagraphs: [
      "GenLayer, AI-native bir Layer 1 blockchain'dir. Bazı uygulamalarda cevap sadece sabit bir hesap değildir; bağlam ve değerlendirme gerekir.",
      "Intelligent Contracts Python ile yazılır ve öğrenme, sertifika, itibar ve topluluk doğrulaması gibi akışlarda kullanılabilir.",
    ],
    listItems: ["AI-native doğrulama", "Python sözleşmeleri", "Bağlam gerektiren kararlar için uygun"],
    calloutTitle: "Topluluk odağı",
    calloutText: "Yerel dilde eğitim, daha fazla üyenin GenLayer ekosistemini anlamasına ve katılmasına yardımcı olur.",
    quizTitle: "Türkçe GenLayer Temel Testi",
    questions: [
      { id: "turkey-q1", prompt: "GenLayer Intelligent Contracts hangi dilde yazılır?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer Intelligent Contracts Python ile yazılır." },
      { id: "turkey-q2", prompt: "GenLayer hangi kararlar için güçlüdür?", options: ["Sadece sabit hesaplar", "Bağlam ve yorum isteyen kararlar", "Sadece dosya saklama", "Doğrulamasız kararlar"], correctOption: 1, explanation: "GenLayer AI-native doğrulama ile subjektif kararları destekler." },
      { id: "turkey-q3", prompt: "Bölgesel öğrenmenin amacı nedir?", options: ["Katılımı azaltmak", "Yerel dilde anlayışı artırmak", "Topluluğu kapatmak", "Pratiği kaldırmak"], correctOption: 1, explanation: "Yerel dil öğrenmeyi daha erişilebilir yapar." },
    ],
  }),
  createRegionalTrack({
    slug: "ukraine",
    regionName: "Ukraine",
    nativeRegionName: "Україна",
    languageName: "Ukrainian",
    nativeLanguageName: "Українська",
    locale: "uk-UA",
    title: "Основи GenLayer українською",
    description: "Вивчайте GenLayer, Python Intelligent Contracts та AI-native валідацію українською.",
    unityMessage: "Українська спільнота вивчає GenLayer рідною мовою і будує разом із глобальною екосистемою.",
    certificateTitle: "Сертифікат GenLayer Basics Ukraine",
    lessonTitle: "Вступ до GenLayer",
    lessonSummary: "Короткий вступ до GenLayer для української спільноти.",
    objectives: ["Зрозуміти GenLayer як AI-native Layer 1.", "Побачити роль Python Intelligent Contracts.", "Пояснити важливість суб'єктивної валідації."],
    knowledgeHeading: "Що таке GenLayer?",
    knowledgeParagraphs: [
      "GenLayer — це AI-native Layer 1 блокчейн для застосунків, де рішення можуть потребувати контексту та оцінки.",
      "Intelligent Contracts пишуться на Python і можуть допомагати з навчанням, сертифікатами, репутацією та прозорими процесами спільноти.",
    ],
    listItems: ["AI-native валідація", "Python контракти", "Корисно для освіти та сертифікації"],
    calloutTitle: "Для спільноти",
    calloutText: "Навчання українською робить GenLayer ближчим і зрозумілішим для нових учасників.",
    quizTitle: "Український тест з основ GenLayer",
    questions: [
      { id: "ukraine-q1", prompt: "Якою мовою пишуться Intelligent Contracts у GenLayer?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "Intelligent Contracts у GenLayer пишуться на Python." },
      { id: "ukraine-q2", prompt: "Для яких рішень GenLayer особливо корисний?", options: ["Тільки фіксована арифметика", "Рішення з контекстом та оцінкою", "Тільки зберігання файлів", "Без валідації"], correctOption: 1, explanation: "GenLayer підтримує AI-native валідацію суб'єктивних рішень." },
      { id: "ukraine-q3", prompt: "Чому важлива регіональна школа?", options: ["Щоб ускладнити навчання", "Щоб навчатися зрозумілою мовою", "Щоб прибрати практику", "Щоб закрити спільноту"], correctOption: 1, explanation: "Рідна мова робить навчання доступнішим." },
    ],
  }),
  createRegionalTrack({
    slug: "vietnam",
    regionName: "Vietnam",
    nativeRegionName: "Việt Nam",
    languageName: "Vietnamese",
    nativeLanguageName: "Tiếng Việt",
    locale: "vi-VN",
    title: "Nền tảng GenLayer bằng Tiếng Việt",
    description: "Học GenLayer, Intelligent Contracts Python và xác thực AI-native bằng Tiếng Việt.",
    unityMessage: "Cộng đồng Việt Nam học bằng tiếng mẹ đẻ và cùng kết nối với hệ sinh thái GenLayer toàn cầu.",
    certificateTitle: "Chứng nhận GenLayer Cơ bản Việt Nam",
    lessonTitle: "Giới thiệu GenLayer",
    lessonSummary: "Hiểu nhanh GenLayer và lý do nó quan trọng cho ứng dụng cần ngữ cảnh.",
    objectives: ["Hiểu GenLayer là Layer 1 AI-native.", "Nhận biết Intelligent Contracts dùng Python.", "Hiểu xác thực chủ quan."],
    knowledgeHeading: "GenLayer là gì?",
    knowledgeParagraphs: [
      "GenLayer là blockchain Layer 1 AI-native. Nó phù hợp với ứng dụng mà câu trả lời cần ngữ cảnh và đánh giá, không chỉ là phép tính cố định.",
      "Intelligent Contracts được viết bằng Python và có thể hỗ trợ học tập, chứng nhận, uy tín và các quy trình cộng đồng minh bạch.",
    ],
    listItems: ["Xác thực AI-native", "Hợp đồng Python", "Phù hợp cho giáo dục và chứng nhận"],
    calloutTitle: "Góc cộng đồng",
    calloutText: "Học bằng ngôn ngữ bản địa giúp nhiều thành viên hiểu GenLayer và tự tin tham gia xây dựng.",
    quizTitle: "Câu hỏi GenLayer Cơ bản Tiếng Việt",
    questions: [
      { id: "vietnam-q1", prompt: "Intelligent Contracts của GenLayer được viết bằng ngôn ngữ nào?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "Intelligent Contracts của GenLayer được viết bằng Python." },
      { id: "vietnam-q2", prompt: "GenLayer mạnh với loại quyết định nào?", options: ["Chỉ phép tính cố định", "Quyết định cần ngữ cảnh và đánh giá", "Chỉ lưu ảnh", "Không cần xác thực"], correctOption: 1, explanation: "GenLayer hỗ trợ xác thực AI-native cho quyết định chủ quan." },
      { id: "vietnam-q3", prompt: "Lợi ích của học theo khu vực là gì?", options: ["Làm khó người học", "Giúp học bằng ngôn ngữ quen thuộc", "Xóa cộng đồng", "Bỏ phần thực hành"], correctOption: 1, explanation: "Ngôn ngữ bản địa giúp kiến thức dễ tiếp cận hơn." },
    ],
  }),
];

export function getRegionalTrack(slug: string): RegionalTrack | null {
  return regionalTracks.find((track) => track.slug === slug) ?? null;
}

export function isRegionSlug(slug: string): slug is RegionSlug {
  return regionalTracks.some((track) => track.slug === slug);
}
