import type { ContentBlock, Lesson, RegionalTrack, RegionSlug } from "./types";

type RegionSeed = Omit<RegionalTrack, "lessons" | "quiz"> & {
  lessonTitle: string;
  lessonSummary: string;
  objectives: string[];
  sections: Array<{
    heading: string;
    body: string;
  }>;
  listTitle: string;
  listItems: string[];
  calloutTitle: string;
  calloutText: string;
  quizTitle: string;
  questions: RegionalTrack["quiz"]["questions"];
};

function createRegionalLesson(region: RegionSeed): Lesson {
  const sectionBlocks = region.sections.flatMap<ContentBlock>((section) => [
    { type: "heading", text: section.heading },
    { type: "paragraph", text: section.body },
  ]);

  return {
    slug: "genlayer-basics",
    title: region.lessonTitle,
    durationMinutes: 16,
    summary: region.lessonSummary,
    objectives: region.objectives,
    content: [
      ...sectionBlocks,
      { type: "heading", text: region.listTitle },
      { type: "list", items: region.listItems },
      { type: "callout", title: region.calloutTitle, text: region.calloutText },
    ],
  };
}

function createRegionalTrack(region: RegionSeed): RegionalTrack {
  return {
    slug: region.slug,
    regionName: region.regionName,
    nativeRegionName: region.nativeRegionName,
    languageName: region.languageName,
    nativeLanguageName: region.nativeLanguageName,
    locale: region.locale,
    title: region.title,
    description: region.description,
    unityMessage: region.unityMessage,
    certificateTitle: region.certificateTitle,
    lessons: [createRegionalLesson(region)],
    quiz: {
      slug: `${region.slug}-genlayer-basics-quiz`,
      title: region.quizTitle,
      passPercent: 70,
      questions: region.questions,
    },
  };
}

export const regionalTracks: RegionalTrack[] = [
  createRegionalTrack({
    slug: "china",
    regionName: "China",
    nativeRegionName: "中国",
    languageName: "Chinese",
    nativeLanguageName: "中文",
    locale: "zh-CN",
    title: "GenLayer 中文基础课",
    description: "用中文学习 GenLayer 生态、AI 原生区块链、Python 智能合约和社区认证。",
    unityMessage: "中国社区用熟悉的语言理解 GenLayer，同时与全球成员一起学习、建设和分享。",
    certificateTitle: "GenLayer 中文基础证书",
    lessonTitle: "GenLayer 生态基础",
    lessonSummary: "了解 GenLayer 是什么、为什么 AI 原生链重要、智能合约如何工作，以及社区成员下一步可以做什么。",
    objectives: [
      "理解 GenLayer 是面向 AI 原生应用的 Layer 1。",
      "认识 Python Intelligent Contracts 的作用。",
      "说明 Optimistic Democracy 如何帮助验证主观问题。",
      "知道学习者、建设者和社区贡献者可以从哪里开始。",
    ],
    sections: [
      { heading: "GenLayer 是什么？", body: "GenLayer 是一个 AI 原生 Layer 1 区块链。传统合约更擅长固定规则，而 GenLayer 关注需要语境、判断和外部信息的应用场景。" },
      { heading: "为什么 AI 原生很重要？", body: "很多真实问题不能只用简单计算回答，例如内容质量、学习成绩、社区贡献或现实世界事件。GenLayer 让链上应用可以把 AI 推理和验证流程结合起来。" },
      { heading: "Intelligent Contracts", body: "GenLayer 的 Intelligent Contracts 使用 Python 编写。Python 对很多开发者更友好，也适合把学习、证书、评分、声誉和社区流程写成透明的链上逻辑。" },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy 是 GenLayer 用来处理主观判断的核心思路：多个验证者可以对 AI 生成或判断型结果进行检查，帮助系统更可信。" },
      { heading: "社区下一步", body: "先理解核心概念，再尝试阅读示例合约、参加社区讨论、完成区域测验，并把学到的内容分享给本地社区。" },
    ],
    listTitle: "你应该记住",
    listItems: ["GenLayer 是 AI 原生 Layer 1。", "Intelligent Contracts 使用 Python。", "GenLayer 适合需要语境和判断的应用。", "区域学习让更多社区成员用母语进入生态。"],
    calloutTitle: "社区重点",
    calloutText: "学习 GenLayer 的目标不是背术语，而是让不同地区的成员都能理解、解释并参与建设这个生态。",
    quizTitle: "GenLayer 中文基础测验",
    questions: [
      { id: "china-q1", prompt: "GenLayer 最适合哪类链上应用？", options: ["只需要固定计算的应用", "需要语境、判断或 AI 验证的应用", "只保存图片的应用", "完全不需要验证的应用"], correctOption: 1, explanation: "GenLayer 的优势是支持需要上下文和判断的 AI 原生应用。" },
      { id: "china-q2", prompt: "GenLayer Intelligent Contracts 主要使用什么语言？", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer Intelligent Contracts 使用 Python 编写。" },
      { id: "china-q3", prompt: "Optimistic Democracy 的作用是什么？", options: ["关闭验证流程", "帮助验证主观或 AI 相关结果", "只处理代币转账", "替代所有社区学习"], correctOption: 1, explanation: "Optimistic Democracy 帮助 GenLayer 处理需要判断的结果验证。" },
      { id: "china-q4", prompt: "区域 GenLayer School 的意义是什么？", options: ["让社区更难学习", "让成员用母语理解 GenLayer", "删除测验", "停止建设"], correctOption: 1, explanation: "母语学习能帮助更多成员理解生态并参与建设。" },
      { id: "china-q5", prompt: "完成基础学习后，社区成员最好的下一步是什么？", options: ["只记价格", "阅读示例、参加讨论并尝试建设", "不再学习", "避免分享知识"], correctOption: 1, explanation: "学习后的价值在于继续实践、讨论和贡献。" },
    ],
  }),
  createRegionalTrack({
    slug: "india",
    regionName: "India",
    nativeRegionName: "भारत",
    languageName: "Hindi",
    nativeLanguageName: "हिन्दी",
    locale: "hi-IN",
    title: "GenLayer हिंदी मूल बातें",
    description: "हिंदी में GenLayer ecosystem, AI-native blockchain, Python Intelligent Contracts और community certificates सीखें।",
    unityMessage: "भारत के सदस्य अपनी भाषा में सीखते हुए GenLayer की global community से जुड़ सकते हैं।",
    certificateTitle: "GenLayer हिंदी बेसिक्स सर्टिफिकेट",
    lessonTitle: "GenLayer ecosystem की बुनियाद",
    lessonSummary: "GenLayer क्या है, AI-native blockchain क्यों matter करता है, Intelligent Contracts कैसे काम करते हैं, और community members आगे क्या कर सकते हैं।",
    objectives: [
      "GenLayer को AI-native Layer 1 के रूप में समझना।",
      "Python Intelligent Contracts की भूमिका पहचानना।",
      "Optimistic Democracy और subjective validation का मतलब समझना।",
      "Regional learning और community contribution का value समझना।",
    ],
    sections: [
      { heading: "GenLayer क्या है?", body: "GenLayer एक AI-native Layer 1 blockchain है। इसका focus उन apps पर है जहाँ answer केवल fixed rule या simple calculation से नहीं मिलता।" },
      { heading: "AI-native क्यों important है?", body: "कई real-world use cases में context, judgment और outside information चाहिए। जैसे certificate verification, subjective quiz grading, reputation, या community contribution review।" },
      { heading: "Intelligent Contracts", body: "GenLayer Intelligent Contracts Python में लिखे जाते हैं। Python familiar होने की वजह से builders learning apps, certification flows और community tools को ज्यादा approachable तरीके से design कर सकते हैं।" },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy GenLayer का validation approach है जहाँ validators subjective या AI-assisted result को check करते हैं ताकि on-chain decision ज्यादा trustworthy हो।" },
      { heading: "Community next step", body: "पहले basics समझें, फिर regional quiz complete करें, GenLayer examples पढ़ें, community discussions join करें और अपनी local language में knowledge share करें।" },
    ],
    listTitle: "याद रखने वाली बातें",
    listItems: ["GenLayer AI-native Layer 1 है।", "Intelligent Contracts Python में लिखे जाते हैं।", "GenLayer context और judgment वाले apps के लिए useful है।", "Regional learning ज्यादा लोगों को ecosystem में लाता है।"],
    calloutTitle: "Community focus",
    calloutText: "Native language में सीखना केवल translation नहीं है; यह ज्यादा members को confidently GenLayer समझने और build करने का रास्ता देता है।",
    quizTitle: "GenLayer हिंदी क्विज",
    questions: [
      { id: "india-q1", prompt: "GenLayer किस तरह की blockchain है?", options: ["AI-native Layer 1", "Only NFT marketplace", "Only file storage", "Centralized database"], correctOption: 0, explanation: "GenLayer एक AI-native Layer 1 blockchain है।" },
      { id: "india-q2", prompt: "GenLayer Intelligent Contracts किस language में लिखे जाते हैं?", options: ["Python", "Solidity", "Cairo", "Move"], correctOption: 0, explanation: "GenLayer Intelligent Contracts Python में लिखे जाते हैं।" },
      { id: "india-q3", prompt: "Optimistic Democracy किसमें मदद करता है?", options: ["Subjective results को validate करने में", "Learning हटाने में", "Only image upload में", "Admin token बनाने में"], correctOption: 0, explanation: "यह subjective या AI-assisted decisions को verify करने में मदद करता है।" },
      { id: "india-q4", prompt: "Regional GenLayer School का benefit क्या है?", options: ["Community को अलग करना", "Native language में समझ बढ़ाना", "Quizzes हटाना", "Builders रोकना"], correctOption: 1, explanation: "Native language learning से ज्यादा लोग ecosystem समझ पाते हैं।" },
      { id: "india-q5", prompt: "Basics के बाद अच्छा next step क्या है?", options: ["Examples पढ़ना और community में participate करना", "Knowledge hide करना", "सिर्फ price देखना", "Quiz avoid करना"], correctOption: 0, explanation: "Practice और community participation learning को useful बनाते हैं।" },
    ],
  }),
  createRegionalTrack({
    slug: "indonesia",
    regionName: "Indonesia",
    nativeRegionName: "Indonesia",
    languageName: "Indonesian",
    nativeLanguageName: "Bahasa Indonesia",
    locale: "id-ID",
    title: "Dasar GenLayer Bahasa Indonesia",
    description: "Pelajari ekosistem GenLayer, blockchain AI-native, Intelligent Contracts Python, dan sertifikat komunitas dalam Bahasa Indonesia.",
    unityMessage: "Komunitas Indonesia belajar dengan bahasa sendiri sambil tetap terhubung dengan ekosistem GenLayer global.",
    certificateTitle: "Sertifikat Dasar GenLayer Indonesia",
    lessonTitle: "Dasar ekosistem GenLayer",
    lessonSummary: "Pahami apa itu GenLayer, mengapa blockchain AI-native penting, cara kerja Intelligent Contracts, dan langkah berikutnya untuk komunitas.",
    objectives: [
      "Menjelaskan GenLayer sebagai Layer 1 AI-native.",
      "Mengenali peran Intelligent Contracts berbasis Python.",
      "Memahami Optimistic Democracy untuk validasi subjektif.",
      "Menentukan langkah awal sebagai pelajar, builder, atau kontributor komunitas.",
    ],
    sections: [
      { heading: "Apa itu GenLayer?", body: "GenLayer adalah blockchain Layer 1 AI-native. GenLayer dibuat untuk aplikasi yang tidak selalu bisa dijawab dengan aturan kaku, karena sebagian keputusan membutuhkan konteks dan penilaian." },
      { heading: "Mengapa AI-native penting?", body: "Banyak proses dunia nyata membutuhkan interpretasi: menilai jawaban, memeriksa kontribusi, menerbitkan sertifikat, atau membaca data dari luar chain. GenLayer membawa kemampuan itu ke alur on-chain." },
      { heading: "Intelligent Contracts", body: "Intelligent Contracts GenLayer ditulis dengan Python. Ini membuat konsep kontrak lebih dekat dengan banyak developer dan cocok untuk membangun pendidikan, reputasi, sertifikasi, dan alat komunitas." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy membantu memvalidasi hasil yang subjektif atau dibantu AI. Ide besarnya adalah keputusan tidak hanya diterima begitu saja, tetapi bisa diperiksa oleh proses validator." },
      { heading: "Langkah komunitas", body: "Mulai dari memahami konsep dasar, menyelesaikan kuis regional, membaca contoh kontrak, lalu berbagi penjelasan sederhana ke anggota komunitas lain." },
    ],
    listTitle: "Poin penting",
    listItems: ["GenLayer adalah Layer 1 AI-native.", "Intelligent Contracts ditulis dengan Python.", "GenLayer cocok untuk aplikasi berbasis konteks.", "Bahasa lokal membantu lebih banyak anggota ikut membangun."],
    calloutTitle: "Untuk komunitas",
    calloutText: "Belajar dalam bahasa lokal membuat GenLayer terasa lebih dekat dan membuka pintu bagi lebih banyak builder dari Indonesia.",
    quizTitle: "Kuis Dasar GenLayer Indonesia",
    questions: [
      { id: "indonesia-q1", prompt: "Apa posisi GenLayer dalam ekosistem blockchain?", options: ["Layer 1 AI-native", "Aplikasi chat biasa", "Database tertutup", "Marketplace gambar saja"], correctOption: 0, explanation: "GenLayer adalah blockchain Layer 1 AI-native." },
      { id: "indonesia-q2", prompt: "Bahasa utama Intelligent Contracts GenLayer adalah apa?", options: ["Python", "Solidity", "Rust", "Move"], correctOption: 0, explanation: "Intelligent Contracts GenLayer ditulis dengan Python." },
      { id: "indonesia-q3", prompt: "Optimistic Democracy membantu apa?", options: ["Memvalidasi keputusan subjektif", "Menghapus komunitas", "Membuat quiz tidak perlu", "Hanya menyimpan gambar"], correctOption: 0, explanation: "Optimistic Democracy membantu validasi hasil yang membutuhkan penilaian." },
      { id: "indonesia-q4", prompt: "Mengapa belajar regional penting?", options: ["Agar lebih sulit", "Agar anggota belajar dengan bahasa yang familiar", "Agar tidak ada sertifikat", "Agar builder berhenti"], correctOption: 1, explanation: "Bahasa lokal membuat konsep lebih mudah dipahami." },
      { id: "indonesia-q5", prompt: "Langkah baik setelah memahami dasar adalah apa?", options: ["Membaca contoh, ikut diskusi, dan mencoba membangun", "Berhenti belajar", "Hanya melihat harga", "Tidak membagikan ilmu"], correctOption: 0, explanation: "Praktik dan diskusi komunitas membuat pembelajaran lebih berguna." },
    ],
  }),
  createRegionalTrack({
    slug: "latam",
    regionName: "LATAM",
    nativeRegionName: "Latinoamérica",
    languageName: "Spanish + Portuguese",
    nativeLanguageName: "Español + Português",
    locale: "es-419",
    title: "Fundamentos de GenLayer para LATAM",
    description: "Aprende GenLayer, blockchain AI-native, contratos inteligentes en Python y certificados comunitarios en español y portugués.",
    unityMessage: "LATAM aprende GenLayer en español y portugués, uniendo comunidades locales con el ecosistema global.",
    certificateTitle: "Certificado GenLayer Básico LATAM",
    lessonTitle: "Fundamentos de GenLayer / Fundamentos do GenLayer",
    lessonSummary: "Una introducción bilingüe para LATAM sobre GenLayer, AI-native blockchain, Intelligent Contracts y participación comunitaria.",
    objectives: [
      "Entender GenLayer como una Layer 1 AI-native / Entender GenLayer como uma Layer 1 AI-native.",
      "Reconocer contratos inteligentes en Python / Reconhecer contratos inteligentes em Python.",
      "Explicar Optimistic Democracy / Explicar Optimistic Democracy.",
      "Conectar aprendizaje regional con participación global / Conectar aprendizado regional com participação global.",
    ],
    sections: [
      { heading: "¿Qué es GenLayer? / O que é GenLayer?", body: "GenLayer es una blockchain Layer 1 AI-native para aplicaciones que necesitan contexto y criterio. GenLayer é uma blockchain Layer 1 AI-native para aplicações que precisam de contexto e julgamento." },
      { heading: "¿Por qué AI-native importa? / Por que AI-native importa?", body: "Muchas decisiones reales no son solo cálculos: evaluar aprendizaje, reputación, contribuciones o datos externos requiere interpretación. Muitas decisões reais não são apenas cálculos: exigem interpretação." },
      { heading: "Intelligent Contracts", body: "Los Intelligent Contracts se escriben en Python y pueden organizar certificados, evaluaciones y herramientas comunitarias verificables. Os Intelligent Contracts são escritos em Python e podem organizar certificados, avaliações e ferramentas comunitárias verificáveis." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy ayuda a revisar resultados subjetivos o asistidos por IA. Optimistic Democracy ajuda a revisar resultados subjetivos ou assistidos por IA." },
      { heading: "Próximo paso / Próximo passo", body: "Completa el quiz regional, lee ejemplos, participa en la comunidad y explica GenLayer en tu idioma local. Complete o quiz regional, leia exemplos, participe da comunidade e explique GenLayer no seu idioma local." },
    ],
    listTitle: "Ideas clave / Ideias-chave",
    listItems: ["GenLayer es una Layer 1 AI-native / GenLayer é uma Layer 1 AI-native.", "Los contratos usan Python / Os contratos usam Python.", "Es útil para decisiones con contexto / É útil para decisões com contexto.", "LATAM puede aprender y construir en español y portugués."],
    calloutTitle: "Mensaje regional / Mensagem regional",
    calloutText: "Aprender en español y portugués ayuda a que más miembros de LATAM participen con confianza en GenLayer.",
    quizTitle: "Quiz GenLayer Básico LATAM / Questionário GenLayer Básico LATAM",
    questions: [
      { id: "latam-q1", prompt: "¿Qué tipo de blockchain es GenLayer? / Que tipo de blockchain é GenLayer?", options: ["Layer 1 AI-native", "Solo una wallet / Apenas uma carteira", "Una base privada / Um banco privado", "Solo almacenamiento / Apenas armazenamento"], correctOption: 0, explanation: "GenLayer es una Layer 1 AI-native / GenLayer é uma Layer 1 AI-native." },
      { id: "latam-q2", prompt: "¿En qué lenguaje se escriben los Intelligent Contracts? / Em qual linguagem são escritos?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "Los Intelligent Contracts de GenLayer usan Python / Os Intelligent Contracts do GenLayer usam Python." },
      { id: "latam-q3", prompt: "¿Qué ayuda a validar Optimistic Democracy? / O que Optimistic Democracy ajuda a validar?", options: ["Resultados subjetivos", "Solo colores / Apenas cores", "Nada / Nada", "Solo logos / Apenas logos"], correctOption: 0, explanation: "Ayuda con decisiones que necesitan criterio / Ajuda com decisões que precisam de julgamento." },
      { id: "latam-q4", prompt: "¿Por qué aprender en idioma regional? / Por que aprender no idioma regional?", options: ["Para reducir participación / Para reduzir participação", "Para que más miembros entiendan / Para que mais membros entendam", "Para eliminar quizzes / Para eliminar quizzes", "Para evitar comunidad / Para evitar comunidade"], correctOption: 1, explanation: "El idioma local mejora acceso y confianza / O idioma local melhora acesso e confiança." },
      { id: "latam-q5", prompt: "Después del básico, ¿qué conviene hacer? / Depois do básico, o que fazer?", options: ["Leer ejemplos y participar / Ler exemplos e participar", "Parar de aprender / Parar de aprender", "Solo mirar precio / Apenas olhar preço", "No compartir / Não compartilhar"], correctOption: 0, explanation: "La práctica y la comunidad convierten aprendizaje en contribución / Prática e comunidade transformam aprendizado em contribuição." },
    ],
  }),
  createRegionalTrack({
    slug: "nigeria",
    regionName: "Nigeria",
    nativeRegionName: "Naija",
    languageName: "Pidgin",
    nativeLanguageName: "Naija Pidgin",
    locale: "pcm-NG",
    title: "GenLayer Basic for Naija Pidgin",
    description: "Learn GenLayer for Pidgin: AI-native chain, Python contracts, Optimistic Democracy, and community certificates.",
    unityMessage: "Naija community fit learn GenLayer for our own voice and still build with the whole world.",
    certificateTitle: "GenLayer Naija Pidgin Basics Certificate",
    lessonTitle: "GenLayer ecosystem basic",
    lessonSummary: "Simple Pidgin intro to wetin GenLayer be, why AI-native chain matter, and how community members fit start.",
    objectives: [
      "Know say GenLayer na AI-native Layer 1.",
      "Understand say Intelligent Contracts dey use Python.",
      "Know wetin Optimistic Democracy dey help validate.",
      "Know how learner or builder fit take next step for community.",
    ],
    sections: [
      { heading: "Wetin be GenLayer?", body: "GenLayer na AI-native Layer 1 blockchain. E dey useful for apps wey answer no be only fixed calculation, but matter need context, judgement, and better verification." },
      { heading: "Why AI-native matter?", body: "Some real-life things need sense-making: grading answer, checking contribution, issuing certificate, or looking at external information. GenLayer dey built for that kind work." },
      { heading: "Intelligent Contracts", body: "GenLayer Intelligent Contracts dey use Python. This fit make am easier for builders to create learning apps, certificate flows, reputation tools, and community systems wey people fit verify." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy na way to help check subjective or AI-assisted result. E no just accept any answer blindly; validation process dey help make result more trusted." },
      { heading: "Next step for Naija community", body: "Finish this lesson, pass quiz, read examples, join community gist, and explain GenLayer to another person for simple language." },
    ],
    listTitle: "Things to remember",
    listItems: ["GenLayer na AI-native Layer 1.", "Intelligent Contracts dey use Python.", "GenLayer good for apps wey need context and judgement.", "Pidgin learning fit bring more Naija members into GenLayer."],
    calloutTitle: "Community sense",
    calloutText: "If person fit learn for language wey e dey comfortable with, e go fit understand fast, ask better questions, and build with confidence.",
    quizTitle: "GenLayer Naija Pidgin Quiz",
    questions: [
      { id: "nigeria-q1", prompt: "GenLayer na wetin?", options: ["AI-native Layer 1 blockchain", "Only picture app", "Central database", "Only chat group"], correctOption: 0, explanation: "GenLayer na AI-native Layer 1 blockchain." },
      { id: "nigeria-q2", prompt: "GenLayer Intelligent Contracts dey use which language?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer Intelligent Contracts dey use Python." },
      { id: "nigeria-q3", prompt: "Optimistic Democracy dey help with wetin?", options: ["Validate subjective or AI-assisted result", "Stop learning", "Only change color", "Remove community"], correctOption: 0, explanation: "E dey help check results wey need judgement." },
      { id: "nigeria-q4", prompt: "Why Pidgin learning matter?", options: ["E make learning harder", "E help more Naija members understand", "E stop builders", "E remove quiz"], correctOption: 1, explanation: "Language wey people know fit help them enter ecosystem." },
      { id: "nigeria-q5", prompt: "After basics, wetin be good next step?", options: ["Read examples, join discussion, try build", "Hide knowledge", "Only watch price", "Avoid community"], correctOption: 0, explanation: "Practice and community discussion dey turn learning to contribution." },
    ],
  }),
  createRegionalTrack({
    slug: "russia",
    regionName: "Russia",
    nativeRegionName: "Россия",
    languageName: "Russian",
    nativeLanguageName: "Русский",
    locale: "ru-RU",
    title: "Основы GenLayer на русском",
    description: "Изучайте экосистему GenLayer, AI-native blockchain, Python Intelligent Contracts и сертификаты сообщества на русском языке.",
    unityMessage: "Русскоязычное сообщество изучает GenLayer на родном языке и остается частью глобального движения.",
    certificateTitle: "Сертификат GenLayer Basics Russia",
    lessonTitle: "Основы экосистемы GenLayer",
    lessonSummary: "Разберитесь, что такое GenLayer, почему важен AI-native blockchain, как работают Intelligent Contracts и что делать дальше.",
    objectives: [
      "Понять GenLayer как AI-native Layer 1.",
      "Узнать роль Python Intelligent Contracts.",
      "Объяснить Optimistic Democracy и субъективную валидацию.",
      "Понять следующие шаги для обучения и участия в сообществе.",
    ],
    sections: [
      { heading: "Что такое GenLayer?", body: "GenLayer - это AI-native Layer 1 блокчейн. Он предназначен для приложений, где решение может требовать контекста, оценки и внешней информации, а не только фиксированных правил." },
      { heading: "Почему важен AI-native подход?", body: "Реальные процессы часто включают субъективные элементы: оценку ответов, вклад участников, сертификаты или данные из внешнего мира. GenLayer помогает переносить такие процессы в проверяемую on-chain логику." },
      { heading: "Intelligent Contracts", body: "Intelligent Contracts в GenLayer пишутся на Python. Это делает обучение и разработку ближе многим участникам и помогает создавать образовательные, репутационные и сертификационные продукты." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy помогает проверять субъективные или AI-assisted результаты через процесс валидации, чтобы решение было более надежным." },
      { heading: "Следующий шаг", body: "Изучите основы, пройдите региональный тест, посмотрите примеры контрактов и попробуйте объяснить GenLayer другому участнику сообщества простыми словами." },
    ],
    listTitle: "Главное",
    listItems: ["GenLayer - AI-native Layer 1.", "Intelligent Contracts пишутся на Python.", "GenLayer подходит для решений с контекстом и оценкой.", "Региональное обучение делает экосистему доступнее."],
    calloutTitle: "Для сообщества",
    calloutText: "Обучение на родном языке помогает большему числу участников понять GenLayer и увереннее включиться в глобальную экосистему.",
    quizTitle: "Тест по основам GenLayer",
    questions: [
      { id: "russia-q1", prompt: "Что такое GenLayer?", options: ["AI-native Layer 1 блокчейн", "Только кошелек", "Закрытая база данных", "Только файловое хранилище"], correctOption: 0, explanation: "GenLayer - это AI-native Layer 1 блокчейн." },
      { id: "russia-q2", prompt: "На каком языке пишутся Intelligent Contracts в GenLayer?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "Intelligent Contracts в GenLayer пишутся на Python." },
      { id: "russia-q3", prompt: "Зачем нужна Optimistic Democracy?", options: ["Для проверки субъективных результатов", "Чтобы убрать валидацию", "Только для дизайна", "Чтобы отключить обучение"], correctOption: 0, explanation: "Она помогает проверять результаты, которые требуют оценки." },
      { id: "russia-q4", prompt: "В чем польза региональной школы?", options: ["Делает обучение понятнее на родном языке", "Разделяет всех участников", "Убирает практику", "Запрещает сертификаты"], correctOption: 0, explanation: "Родной язык делает обучение доступнее." },
      { id: "russia-q5", prompt: "Что стоит сделать после основ?", options: ["Изучать примеры и участвовать в обсуждениях", "Скрывать знания", "Смотреть только цену", "Не проходить тест"], correctOption: 0, explanation: "Практика и обсуждение превращают знания в вклад." },
    ],
  }),
  createRegionalTrack({
    slug: "korea",
    regionName: "Korea",
    nativeRegionName: "한국",
    languageName: "Korean",
    nativeLanguageName: "한국어",
    locale: "ko-KR",
    title: "GenLayer 한국어 기초",
    description: "한국어로 GenLayer 생태계, AI-native blockchain, Python Intelligent Contracts, 커뮤니티 인증서를 배웁니다.",
    unityMessage: "한국 커뮤니티가 한국어로 배우고 전 세계 GenLayer 커뮤니티와 함께 성장합니다.",
    certificateTitle: "GenLayer 한국어 기초 인증서",
    lessonTitle: "GenLayer 생태계 기초",
    lessonSummary: "GenLayer가 무엇인지, AI-native blockchain이 왜 중요한지, Intelligent Contracts와 커뮤니티 참여가 어떻게 연결되는지 배웁니다.",
    objectives: [
      "GenLayer를 AI-native Layer 1으로 이해하기.",
      "Python Intelligent Contracts의 역할 이해하기.",
      "Optimistic Democracy와 주관적 검증 이해하기.",
      "지역 학습 이후의 커뮤니티 참여 방법 알기.",
    ],
    sections: [
      { heading: "GenLayer란 무엇인가요?", body: "GenLayer는 AI-native Layer 1 블록체인입니다. 고정 규칙만으로 해결하기 어려운 문제, 즉 문맥과 판단이 필요한 애플리케이션을 위해 설계되었습니다." },
      { heading: "AI-native가 중요한 이유", body: "학습 평가, 커뮤니티 기여, 인증서 발급, 외부 정보 해석 같은 실제 문제는 단순 계산만으로 충분하지 않습니다. GenLayer는 이런 판단을 검증 가능한 흐름으로 연결합니다." },
      { heading: "Intelligent Contracts", body: "GenLayer의 Intelligent Contracts는 Python으로 작성됩니다. 교육, 평판, 인증서, 커뮤니티 도구를 더 접근하기 쉬운 방식으로 만들 수 있습니다." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy는 주관적이거나 AI가 도운 결과를 검증하는 접근 방식입니다. 여러 검증 과정을 통해 결과의 신뢰도를 높입니다." },
      { heading: "다음 단계", body: "기초를 이해한 뒤 지역 퀴즈를 완료하고 예시 계약을 읽어보며, 커뮤니티에서 배운 내용을 한국어로 설명해 보세요." },
    ],
    listTitle: "핵심 정리",
    listItems: ["GenLayer는 AI-native Layer 1입니다.", "Intelligent Contracts는 Python을 사용합니다.", "GenLayer는 문맥과 판단이 필요한 앱에 적합합니다.", "지역 언어 학습은 더 많은 참여를 만듭니다."],
    calloutTitle: "커뮤니티 메시지",
    calloutText: "모국어로 배우면 더 많은 구성원이 GenLayer를 이해하고 자신 있게 글로벌 생태계에 참여할 수 있습니다.",
    quizTitle: "GenLayer 한국어 기초 퀴즈",
    questions: [
      { id: "korea-q1", prompt: "GenLayer는 어떤 종류의 블록체인인가요?", options: ["AI-native Layer 1", "일반 채팅 앱", "중앙화 데이터베이스", "이미지 저장소"], correctOption: 0, explanation: "GenLayer는 AI-native Layer 1 블록체인입니다." },
      { id: "korea-q2", prompt: "GenLayer Intelligent Contracts는 어떤 언어를 사용하나요?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer Intelligent Contracts는 Python으로 작성됩니다." },
      { id: "korea-q3", prompt: "Optimistic Democracy는 무엇을 돕나요?", options: ["주관적 결과 검증", "학습 삭제", "색상 변경만", "커뮤니티 제거"], correctOption: 0, explanation: "문맥과 판단이 필요한 결과를 검증하는 데 도움을 줍니다." },
      { id: "korea-q4", prompt: "지역별 학습의 장점은 무엇인가요?", options: ["모국어로 접근성을 높임", "참여를 막음", "퀴즈를 없앰", "인증서를 제거함"], correctOption: 0, explanation: "모국어 학습은 더 넓은 참여를 만듭니다." },
      { id: "korea-q5", prompt: "기초 이후 좋은 다음 단계는 무엇인가요?", options: ["예시를 읽고 커뮤니티에 참여하기", "배움을 멈추기", "가격만 보기", "지식 공유를 피하기"], correctOption: 0, explanation: "실습과 커뮤니티 참여가 학습을 실제 기여로 바꿉니다." },
    ],
  }),
  createRegionalTrack({
    slug: "turkey",
    regionName: "Turkey",
    nativeRegionName: "Türkiye",
    languageName: "Turkish",
    nativeLanguageName: "Türkçe",
    locale: "tr-TR",
    title: "Türkçe GenLayer Temelleri",
    description: "GenLayer ekosistemini, AI-native blockchain yapısını, Python Intelligent Contracts ve topluluk sertifikalarını Türkçe öğrenin.",
    unityMessage: "Türkiye topluluğu kendi dilinde öğrenirken küresel GenLayer topluluğuyla birlikte hareket eder.",
    certificateTitle: "GenLayer Türkiye Temel Sertifikası",
    lessonTitle: "GenLayer ekosistem temelleri",
    lessonSummary: "GenLayer nedir, AI-native blockchain neden önemlidir, Intelligent Contracts nasıl çalışır ve topluluk nasıl başlayabilir?",
    objectives: [
      "GenLayer'ı AI-native Layer 1 olarak anlamak.",
      "Python Intelligent Contracts rolünü tanımak.",
      "Optimistic Democracy ve subjektif doğrulamayı açıklamak.",
      "Bölgesel öğrenmeden topluluk katkısına geçişi görmek.",
    ],
    sections: [
      { heading: "GenLayer nedir?", body: "GenLayer, AI-native bir Layer 1 blockchain'dir. Sabit kurallarla çözülemeyen, bağlam ve yorum gerektiren uygulamalar için tasarlanmıştır." },
      { heading: "AI-native neden önemlidir?", body: "Eğitim değerlendirmesi, sertifika, itibar veya gerçek dünya verileri gibi süreçlerde bazen yorum gerekir. GenLayer bu yorum gerektiren akışları doğrulanabilir hale getirmeyi hedefler." },
      { heading: "Intelligent Contracts", body: "GenLayer Intelligent Contracts Python ile yazılır. Bu, eğitim ürünleri, sertifika akışları ve topluluk araçları geliştirmek isteyen builder'lar için daha erişilebilir bir başlangıç sağlar." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy, subjektif veya AI destekli sonuçların doğrulanmasına yardımcı olan yaklaşımdır. Amaç, kararların daha güvenilir bir süreçten geçmesidir." },
      { heading: "Sonraki adım", body: "Temelleri öğrendikten sonra bölgesel testi tamamlayın, örnek kontratları inceleyin, topluluk tartışmalarına katılın ve GenLayer'ı Türkçe anlatmaya çalışın." },
    ],
    listTitle: "Aklında kalsın",
    listItems: ["GenLayer AI-native Layer 1'dir.", "Intelligent Contracts Python kullanır.", "GenLayer bağlam ve yorum isteyen uygulamalar için uygundur.", "Yerel dilde öğrenmek topluluk katılımını artırır."],
    calloutTitle: "Topluluk odağı",
    calloutText: "Türkçe öğrenme yolu, daha fazla üyenin GenLayer'ı anlamasına ve küresel ekosisteme güvenle katılmasına yardımcı olur.",
    quizTitle: "Türkçe GenLayer Temel Testi",
    questions: [
      { id: "turkey-q1", prompt: "GenLayer nasıl bir blockchain'dir?", options: ["AI-native Layer 1", "Sadece cüzdan", "Kapalı veritabanı", "Sadece dosya deposu"], correctOption: 0, explanation: "GenLayer AI-native bir Layer 1 blockchain'dir." },
      { id: "turkey-q2", prompt: "GenLayer Intelligent Contracts hangi dilde yazılır?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "GenLayer Intelligent Contracts Python ile yazılır." },
      { id: "turkey-q3", prompt: "Optimistic Democracy neye yardımcı olur?", options: ["Subjektif sonuçları doğrulamaya", "Eğitimi durdurmaya", "Sadece tasarıma", "Topluluğu kaldırmaya"], correctOption: 0, explanation: "Yorum gerektiren sonuçların doğrulanmasına yardımcı olur." },
      { id: "turkey-q4", prompt: "Bölgesel öğrenmenin faydası nedir?", options: ["Yerel dilde anlayışı artırır", "Katılımı azaltır", "Quizleri siler", "Sertifikayı kaldırır"], correctOption: 0, explanation: "Yerel dil öğrenmeyi daha erişilebilir yapar." },
      { id: "turkey-q5", prompt: "Temelden sonra iyi bir adım nedir?", options: ["Örnekleri okumak ve topluluğa katılmak", "Öğrenmeyi bırakmak", "Sadece fiyat izlemek", "Bilgiyi paylaşmamak"], correctOption: 0, explanation: "Pratik ve topluluk, öğrenmeyi katkıya dönüştürür." },
    ],
  }),
  createRegionalTrack({
    slug: "ukraine",
    regionName: "Ukraine",
    nativeRegionName: "Україна",
    languageName: "Ukrainian",
    nativeLanguageName: "Українська",
    locale: "uk-UA",
    title: "Основи GenLayer українською",
    description: "Вивчайте екосистему GenLayer, AI-native blockchain, Python Intelligent Contracts та сертифікати спільноти українською.",
    unityMessage: "Українська спільнота вивчає GenLayer рідною мовою і будує разом із глобальною екосистемою.",
    certificateTitle: "Сертифікат GenLayer Basics Ukraine",
    lessonTitle: "Основи екосистеми GenLayer",
    lessonSummary: "Дізнайтеся, що таке GenLayer, чому важливий AI-native blockchain, як працюють Intelligent Contracts і що робити далі.",
    objectives: [
      "Зрозуміти GenLayer як AI-native Layer 1.",
      "Побачити роль Python Intelligent Contracts.",
      "Пояснити Optimistic Democracy і суб'єктивну валідацію.",
      "Зрозуміти наступні кроки для навчання та участі у спільноті.",
    ],
    sections: [
      { heading: "Що таке GenLayer?", body: "GenLayer - це AI-native Layer 1 блокчейн. Він створений для застосунків, де рішення можуть потребувати контексту, оцінки та зовнішньої інформації." },
      { heading: "Чому AI-native важливий?", body: "Оцінювання навчання, внеску учасників, сертифікатів або даних з реального світу часто потребує інтерпретації. GenLayer допомагає зробити такі процеси перевірюваними on-chain." },
      { heading: "Intelligent Contracts", body: "Intelligent Contracts у GenLayer пишуться на Python. Це може зробити освітні, репутаційні та сертифікаційні продукти доступнішими для builder'ів." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy допомагає перевіряти суб'єктивні або AI-assisted результати через процес валідації, щоб рішення були більш надійними." },
      { heading: "Наступний крок", body: "Вивчіть основи, пройдіть регіональний тест, подивіться приклади контрактів і спробуйте пояснити GenLayer іншому учаснику українською." },
    ],
    listTitle: "Головне",
    listItems: ["GenLayer - AI-native Layer 1.", "Intelligent Contracts використовують Python.", "GenLayer підходить для рішень із контекстом та оцінкою.", "Регіональне навчання робить екосистему доступнішою."],
    calloutTitle: "Для спільноти",
    calloutText: "Навчання українською робить GenLayer зрозумілішим і допомагає більшій кількості учасників долучитися до глобального руху.",
    quizTitle: "Український тест з основ GenLayer",
    questions: [
      { id: "ukraine-q1", prompt: "Що таке GenLayer?", options: ["AI-native Layer 1 блокчейн", "Тільки гаманець", "Закрита база даних", "Тільки сховище файлів"], correctOption: 0, explanation: "GenLayer - це AI-native Layer 1 блокчейн." },
      { id: "ukraine-q2", prompt: "Якою мовою пишуться Intelligent Contracts у GenLayer?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "Intelligent Contracts у GenLayer пишуться на Python." },
      { id: "ukraine-q3", prompt: "Для чого потрібна Optimistic Democracy?", options: ["Для валідації суб'єктивних результатів", "Щоб прибрати навчання", "Тільки для дизайну", "Щоб закрити спільноту"], correctOption: 0, explanation: "Вона допомагає перевіряти результати, які потребують оцінки." },
      { id: "ukraine-q4", prompt: "Чому важлива регіональна школа?", options: ["Вона робить навчання доступнішим рідною мовою", "Вона зменшує участь", "Вона видаляє тести", "Вона забороняє сертифікати"], correctOption: 0, explanation: "Рідна мова допомагає швидше зрозуміти складні концепції." },
      { id: "ukraine-q5", prompt: "Що варто зробити після основ?", options: ["Читати приклади і брати участь у спільноті", "Зупинити навчання", "Дивитися лише ціну", "Не ділитися знаннями"], correctOption: 0, explanation: "Практика і спільнота перетворюють знання на внесок." },
    ],
  }),
  createRegionalTrack({
    slug: "vietnam",
    regionName: "Vietnam",
    nativeRegionName: "Việt Nam",
    languageName: "Vietnamese",
    nativeLanguageName: "Tiếng Việt",
    locale: "vi-VN",
    title: "Nền tảng GenLayer bằng Tiếng Việt",
    description: "Học hệ sinh thái GenLayer, blockchain AI-native, Intelligent Contracts Python và chứng nhận cộng đồng bằng Tiếng Việt.",
    unityMessage: "Cộng đồng Việt Nam học bằng tiếng mẹ đẻ và cùng kết nối với hệ sinh thái GenLayer toàn cầu.",
    certificateTitle: "Chứng nhận GenLayer Cơ bản Việt Nam",
    lessonTitle: "Nền tảng hệ sinh thái GenLayer",
    lessonSummary: "Hiểu GenLayer là gì, vì sao blockchain AI-native quan trọng, Intelligent Contracts hoạt động thế nào và cộng đồng có thể bắt đầu ra sao.",
    objectives: [
      "Hiểu GenLayer là Layer 1 AI-native.",
      "Nhận biết vai trò của Python Intelligent Contracts.",
      "Giải thích Optimistic Democracy và xác thực chủ quan.",
      "Biết bước tiếp theo cho người học và cộng đồng.",
    ],
    sections: [
      { heading: "GenLayer là gì?", body: "GenLayer là blockchain Layer 1 AI-native. Nó phù hợp với ứng dụng cần ngữ cảnh, đánh giá và thông tin bên ngoài, không chỉ là phép tính cố định." },
      { heading: "Vì sao AI-native quan trọng?", body: "Nhiều quy trình thực tế như chấm điểm, chứng nhận, uy tín cộng đồng hoặc kiểm tra đóng góp cần sự diễn giải. GenLayer giúp đưa các quy trình đó vào logic on-chain có thể kiểm chứng." },
      { heading: "Intelligent Contracts", body: "Intelligent Contracts của GenLayer được viết bằng Python. Điều này giúp builder dễ tiếp cận hơn khi xây dựng sản phẩm giáo dục, chứng nhận, danh tiếng và công cụ cộng đồng." },
      { heading: "Optimistic Democracy", body: "Optimistic Democracy hỗ trợ xác thực kết quả mang tính chủ quan hoặc có AI hỗ trợ. Mục tiêu là giúp quyết định đáng tin cậy hơn thông qua quá trình validator." },
      { heading: "Bước tiếp theo", body: "Hoàn thành bài học, làm quiz khu vực, đọc ví dụ hợp đồng, tham gia cộng đồng và thử giải thích GenLayer bằng Tiếng Việt cho người khác." },
    ],
    listTitle: "Điểm cần nhớ",
    listItems: ["GenLayer là Layer 1 AI-native.", "Intelligent Contracts dùng Python.", "GenLayer phù hợp với ứng dụng cần ngữ cảnh và đánh giá.", "Học bằng ngôn ngữ địa phương giúp cộng đồng phát triển rộng hơn."],
    calloutTitle: "Góc cộng đồng",
    calloutText: "Học bằng Tiếng Việt giúp nhiều thành viên tự tin hơn khi bước vào hệ sinh thái GenLayer và đóng góp cho cộng đồng toàn cầu.",
    quizTitle: "Câu hỏi GenLayer Cơ bản Tiếng Việt",
    questions: [
      { id: "vietnam-q1", prompt: "GenLayer là loại blockchain nào?", options: ["Layer 1 AI-native", "Chỉ là ví", "Cơ sở dữ liệu đóng", "Chỉ lưu tệp"], correctOption: 0, explanation: "GenLayer là blockchain Layer 1 AI-native." },
      { id: "vietnam-q2", prompt: "Intelligent Contracts của GenLayer dùng ngôn ngữ nào?", options: ["Python", "Solidity", "Move", "Rust"], correctOption: 0, explanation: "Intelligent Contracts của GenLayer được viết bằng Python." },
      { id: "vietnam-q3", prompt: "Optimistic Democracy giúp điều gì?", options: ["Xác thực kết quả chủ quan", "Xóa bài học", "Chỉ đổi màu", "Đóng cộng đồng"], correctOption: 0, explanation: "Nó hỗ trợ xác thực các quyết định cần đánh giá." },
      { id: "vietnam-q4", prompt: "Lợi ích của học theo khu vực là gì?", options: ["Học dễ tiếp cận hơn bằng ngôn ngữ quen thuộc", "Làm khó người học", "Xóa chứng nhận", "Ngăn builder"], correctOption: 0, explanation: "Ngôn ngữ quen thuộc giúp nhiều người hiểu nhanh hơn." },
      { id: "vietnam-q5", prompt: "Sau phần cơ bản, bước tốt là gì?", options: ["Đọc ví dụ, tham gia thảo luận và thử xây dựng", "Dừng học", "Chỉ xem giá", "Không chia sẻ kiến thức"], correctOption: 0, explanation: "Thực hành và cộng đồng giúp kiến thức trở thành đóng góp." },
    ],
  }),
];

export function getRegionalTrack(slug: string): RegionalTrack | null {
  return regionalTracks.find((track) => track.slug === slug) ?? null;
}

export function isRegionSlug(slug: string): slug is RegionSlug {
  return regionalTracks.some((track) => track.slug === slug);
}
